// <auto-generated />
using System;
using Drive.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drive.Data.Migrations
{
    [DbContext(typeof(DriveDbContext))]
    partial class DriveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drive.Data.Entities.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentFolderId")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Some random text.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9205),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9206),
                            Name = "TodoList",
                            OwnerId = 1,
                            ParentFolderId = 1,
                            Size = 20L
                        },
                        new
                        {
                            Id = 2,
                            Content = "Some project planning text.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9209),
                            Extension = "docx",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9209),
                            Name = "ProjectPlan",
                            OwnerId = 1,
                            ParentFolderId = 1,
                            Size = 40L
                        },
                        new
                        {
                            Id = 3,
                            Content = "Work proposal document.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9211),
                            Extension = "pdf",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9211),
                            Name = "WorkProposal",
                            OwnerId = 1,
                            ParentFolderId = 13,
                            Size = 50L
                        },
                        new
                        {
                            Id = 4,
                            Content = "Task list for the week.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9212),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9213),
                            Name = "TaskList",
                            OwnerId = 1,
                            ParentFolderId = 14,
                            Size = 30L
                        },
                        new
                        {
                            Id = 5,
                            Content = "Profile picture.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9214),
                            Extension = "jpg",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9214),
                            Name = "ProfilePicture",
                            OwnerId = 1,
                            ParentFolderId = 15,
                            Size = 15L
                        },
                        new
                        {
                            Id = 6,
                            Content = "Design document draft.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9215),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9216),
                            Name = "DesignDoc",
                            OwnerId = 2,
                            ParentFolderId = 2,
                            Size = 25L
                        },
                        new
                        {
                            Id = 7,
                            Content = "Project financial plan.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9217),
                            Extension = "xlsx",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9217),
                            Name = "ProjectPlan",
                            OwnerId = 2,
                            ParentFolderId = 2,
                            Size = 35L
                        },
                        new
                        {
                            Id = 8,
                            Content = "Meeting notes from last session.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9218),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9218),
                            Name = "MeetingNotes",
                            OwnerId = 2,
                            ParentFolderId = 18,
                            Size = 20L
                        },
                        new
                        {
                            Id = 9,
                            Content = "Financial report for Q1.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9219),
                            Extension = "pdf",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9219),
                            Name = "Report",
                            OwnerId = 2,
                            ParentFolderId = 18,
                            Size = 40L
                        },
                        new
                        {
                            Id = 10,
                            Content = "List of gift ideas for birthday.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9220),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9221),
                            Name = "BirthdayGiftIdeas",
                            OwnerId = 2,
                            ParentFolderId = 19,
                            Size = 15L
                        },
                        new
                        {
                            Id = 11,
                            Content = "Vacation plan spreadsheet.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9222),
                            Extension = "xlsx",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9222),
                            Name = "VacationPlan",
                            OwnerId = 2,
                            ParentFolderId = 20,
                            Size = 50L
                        },
                        new
                        {
                            Id = 12,
                            Content = "Agenda for the meeting.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9223),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9223),
                            Name = "MeetingAgenda",
                            OwnerId = 3,
                            ParentFolderId = 3,
                            Size = 25L
                        },
                        new
                        {
                            Id = 13,
                            Content = "Project status report.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9224),
                            Extension = "docx",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9224),
                            Name = "StatusReport",
                            OwnerId = 3,
                            ParentFolderId = 3,
                            Size = 30L
                        },
                        new
                        {
                            Id = 14,
                            Content = "Compressed source code.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9225),
                            Extension = "zip",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9226),
                            Name = "CodeFiles",
                            OwnerId = 3,
                            ParentFolderId = 23,
                            Size = 100L
                        },
                        new
                        {
                            Id = 15,
                            Content = "Server log files.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9226),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9227),
                            Name = "ServerLogs",
                            OwnerId = 3,
                            ParentFolderId = 24,
                            Size = 150L
                        },
                        new
                        {
                            Id = 16,
                            Content = "Race results from 2023 season.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9228),
                            Extension = "csv",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9228),
                            Name = "RaceResults",
                            OwnerId = 4,
                            ParentFolderId = 4,
                            Size = 40L
                        },
                        new
                        {
                            Id = 17,
                            Content = "Driver performance stats.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9229),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9229),
                            Name = "DriverStats",
                            OwnerId = 4,
                            ParentFolderId = 4,
                            Size = 30L
                        },
                        new
                        {
                            Id = 18,
                            Content = "Detailed results for 2023.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9230),
                            Extension = "xlsx",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9231),
                            Name = "Season2023Results",
                            OwnerId = 4,
                            ParentFolderId = 28,
                            Size = 80L
                        },
                        new
                        {
                            Id = 19,
                            Content = "Detailed results for 2022.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9232),
                            Extension = "xlsx",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9232),
                            Name = "Season2022Results",
                            OwnerId = 4,
                            ParentFolderId = 29,
                            Size = 75L
                        },
                        new
                        {
                            Id = 20,
                            Content = "Podium photo from the 2023 season.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9233),
                            Extension = "jpg",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9233),
                            Name = "PodiumPhoto1",
                            OwnerId = 4,
                            ParentFolderId = 30,
                            Size = 20L
                        },
                        new
                        {
                            Id = 21,
                            Content = "Track 1 from the album.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9234),
                            Extension = "mp3",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9235),
                            Name = "MusicTrack1",
                            OwnerId = 5,
                            ParentFolderId = 5,
                            Size = 40L
                        },
                        new
                        {
                            Id = 22,
                            Content = "Playlist of favorite tracks.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9238),
                            Extension = "m3u",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9238),
                            Name = "Playlist1",
                            OwnerId = 5,
                            ParentFolderId = 5,
                            Size = 10L
                        },
                        new
                        {
                            Id = 23,
                            Content = "Official music video.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9239),
                            Extension = "mp4",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9239),
                            Name = "MusicVideo1",
                            OwnerId = 5,
                            ParentFolderId = 33,
                            Size = 100L
                        },
                        new
                        {
                            Id = 24,
                            Content = "Concert footage.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9240),
                            Extension = "mp4",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9241),
                            Name = "Concert1",
                            OwnerId = 5,
                            ParentFolderId = 35,
                            Size = 250L
                        },
                        new
                        {
                            Id = 25,
                            Content = "Game installation file.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9241),
                            Extension = "exe",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9242),
                            Name = "GameInstall",
                            OwnerId = 6,
                            ParentFolderId = 6,
                            Size = 200L
                        },
                        new
                        {
                            Id = 26,
                            Content = "Zip file of old projects.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9243),
                            Extension = "zip",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9243),
                            Name = "CompressedFiles",
                            OwnerId = 6,
                            ParentFolderId = 6,
                            Size = 300L
                        },
                        new
                        {
                            Id = 27,
                            Content = "Software installer package.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9244),
                            Extension = "exe",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9244),
                            Name = "SoftwareInstaller",
                            OwnerId = 6,
                            ParentFolderId = 38,
                            Size = 150L
                        },
                        new
                        {
                            Id = 28,
                            Content = "Old compressed archives.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9245),
                            Extension = "zip",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9245),
                            Name = "OldArchives",
                            OwnerId = 6,
                            ParentFolderId = 40,
                            Size = 500L
                        },
                        new
                        {
                            Id = 29,
                            Content = "Save game file.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9246),
                            Extension = "sav",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9247),
                            Name = "GameSave1",
                            OwnerId = 7,
                            ParentFolderId = 7,
                            Size = 100L
                        },
                        new
                        {
                            Id = 30,
                            Content = "Save game file 2.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9248),
                            Extension = "sav",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9248),
                            Name = "GameSave2",
                            OwnerId = 7,
                            ParentFolderId = 7,
                            Size = 120L
                        },
                        new
                        {
                            Id = 31,
                            Content = "Mods for the game.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9249),
                            Extension = "zip",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9249),
                            Name = "GameMods",
                            OwnerId = 7,
                            ParentFolderId = 43,
                            Size = 50L
                        },
                        new
                        {
                            Id = 32,
                            Content = "Configuration file for the game.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9250),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9250),
                            Name = "ConfigFile",
                            OwnerId = 7,
                            ParentFolderId = 45,
                            Size = 15L
                        },
                        new
                        {
                            Id = 33,
                            Content = "Lap times for 2023 season.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9251),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9252),
                            Name = "LapTimes2023",
                            OwnerId = 8,
                            ParentFolderId = 8,
                            Size = 20L
                        },
                        new
                        {
                            Id = 34,
                            Content = "Telemetry data for season 2023.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9253),
                            Extension = "csv",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9253),
                            Name = "TelemetryData",
                            OwnerId = 8,
                            ParentFolderId = 8,
                            Size = 40L
                        },
                        new
                        {
                            Id = 35,
                            Content = "Lap time analysis for 2023.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9254),
                            Extension = "xlsx",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9254),
                            Name = "LapTimeAnalysis",
                            OwnerId = 8,
                            ParentFolderId = 49,
                            Size = 60L
                        },
                        new
                        {
                            Id = 36,
                            Content = "Car setups for season 2023.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9255),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9255),
                            Name = "CarSetups2023",
                            OwnerId = 8,
                            ParentFolderId = 50,
                            Size = 50L
                        },
                        new
                        {
                            Id = 37,
                            Content = "Random notes for project.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9256),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9256),
                            Name = "Notes1",
                            OwnerId = 9,
                            ParentFolderId = 9,
                            Size = 20L
                        },
                        new
                        {
                            Id = 38,
                            Content = "Ideas for the new project.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9258),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9258),
                            Name = "Ideas",
                            OwnerId = 9,
                            ParentFolderId = 9,
                            Size = 25L
                        },
                        new
                        {
                            Id = 39,
                            Content = "Draft of a new idea.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9259),
                            Extension = "txt",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9259),
                            Name = "IdeaDraft",
                            OwnerId = 9,
                            ParentFolderId = 53,
                            Size = 30L
                        },
                        new
                        {
                            Id = 40,
                            Content = "Draft of project plan.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9260),
                            Extension = "docx",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9260),
                            Name = "ProjectPlanDraft",
                            OwnerId = 9,
                            ParentFolderId = 54,
                            Size = 40L
                        },
                        new
                        {
                            Id = 41,
                            Content = "Log file 1.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9261),
                            Extension = "log",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9261),
                            Name = "LogFile1",
                            OwnerId = 10,
                            ParentFolderId = 10,
                            Size = 10L
                        },
                        new
                        {
                            Id = 42,
                            Content = "Cache data file.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9262),
                            Extension = "dat",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9262),
                            Name = "CacheFile",
                            OwnerId = 10,
                            ParentFolderId = 10,
                            Size = 50L
                        },
                        new
                        {
                            Id = 43,
                            Content = "Error log for system.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9263),
                            Extension = "log",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9264),
                            Name = "ErrorLog1",
                            OwnerId = 10,
                            ParentFolderId = 58,
                            Size = 30L
                        },
                        new
                        {
                            Id = 44,
                            Content = "Session log file.",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9264),
                            Extension = "log",
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9265),
                            Name = "SessionLog1",
                            OwnerId = 10,
                            ParentFolderId = 60,
                            Size = 60L
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.FileComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("FileId");

                    b.ToTable("FileComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "Some random comment",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9373),
                            FileId = 1,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9374)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Content = "Even more random comment",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9378),
                            FileId = 1,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9378)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Content = "This is another comment",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9379),
                            FileId = 2,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9379)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Content = "A detailed comment",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9380),
                            FileId = 3,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9380)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            Content = "Comment on the file",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9381),
                            FileId = 4,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9381)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            Content = "Great file!",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9382),
                            FileId = 5,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9383)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            Content = "Helpful document",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9383),
                            FileId = 6,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9384)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            Content = "Awesome project plan",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9384),
                            FileId = 7,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9385)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            Content = "Interesting design doc",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9385),
                            FileId = 8,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9385)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 10,
                            Content = "I like this idea",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9386),
                            FileId = 9,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9387)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            Content = "Great report",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9387),
                            FileId = 10,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9388)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 2,
                            Content = "Very detailed race results",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9388),
                            FileId = 11,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9388)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            Content = "Noticed a typo",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9389),
                            FileId = 12,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9389)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 4,
                            Content = "I agree with this analysis",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9390),
                            FileId = 13,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9390)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 5,
                            Content = "This is a useful document",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9391),
                            FileId = 14,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9391)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 6,
                            Content = "Needs revision",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9392),
                            FileId = 15,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9392)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 7,
                            Content = "Just saved this!",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9393),
                            FileId = 16,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9393)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 8,
                            Content = "Great game save!",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9394),
                            FileId = 17,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9394)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 9,
                            Content = "Good configuration",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9395),
                            FileId = 18,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9395)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 10,
                            Content = "Loving these game mods",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9396),
                            FileId = 19,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9396)
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 1,
                            Content = "Can’t wait to try this",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9397),
                            FileId = 20,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9397)
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 2,
                            Content = "Awesome backup!",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9398),
                            FileId = 21,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9398)
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 3,
                            Content = "Very useful file",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9398),
                            FileId = 22,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9399)
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 4,
                            Content = "Nice code files",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9399),
                            FileId = 23,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9400)
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 5,
                            Content = "Logs are clean",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9400),
                            FileId = 24,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9401)
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 6,
                            Content = "Great analysis",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9401),
                            FileId = 25,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9401)
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 7,
                            Content = "Perfect telemetry data",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9402),
                            FileId = 26,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9402)
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 8,
                            Content = "Season 2022 results are helpful",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9403),
                            FileId = 27,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9403)
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 9,
                            Content = "Old project plans",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9404),
                            FileId = 28,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9404)
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 10,
                            Content = "Very useful compressed files",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9405),
                            FileId = 29,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9405)
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 1,
                            Content = "Nice install files",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9406),
                            FileId = 30,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9406)
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 2,
                            Content = "Game data is great",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9406),
                            FileId = 31,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9407)
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 3,
                            Content = "This game setup is useful",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9407),
                            FileId = 32,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9408)
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 4,
                            Content = "Enjoying the music",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9409),
                            FileId = 33,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9409)
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 5,
                            Content = "Great concert footage",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9410),
                            FileId = 34,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9410)
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 6,
                            Content = "Fantastic lap times",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9411),
                            FileId = 35,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9411)
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 7,
                            Content = "Really insightful lap time analysis",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9412),
                            FileId = 36,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9412)
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 8,
                            Content = "Love the car setups",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9412),
                            FileId = 37,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9413)
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 9,
                            Content = "Interesting ideas",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9413),
                            FileId = 38,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9414)
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 10,
                            Content = "Looking forward to this draft",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9414),
                            FileId = 39,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9415)
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 1,
                            Content = "Very helpful file",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9415),
                            FileId = 40,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9415)
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 2,
                            Content = "Great for new ideas",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9416),
                            FileId = 41,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9416)
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 3,
                            Content = "Useful error logs",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9417),
                            FileId = 42,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9417)
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 4,
                            Content = "Session logs look good",
                            CreatedOn = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9418),
                            FileId = 43,
                            LastChanged = new DateTime(2025, 1, 3, 20, 34, 50, 493, DateTimeKind.Utc).AddTicks(9418)
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("OwnerId", "ParentFolderId")
                        .IsUnique()
                        .HasFilter("\"ParentFolderId\" IS NULL");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "root",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "root",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "root",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "root",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "root",
                            OwnerId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "root",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "root",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "root",
                            OwnerId = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "root",
                            OwnerId = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "root",
                            OwnerId = 10
                        },
                        new
                        {
                            Id = 11,
                            Name = "Documents",
                            OwnerId = 1,
                            ParentFolderId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Images",
                            OwnerId = 1,
                            ParentFolderId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Work",
                            OwnerId = 1,
                            ParentFolderId = 11
                        },
                        new
                        {
                            Id = 14,
                            Name = "Projects",
                            OwnerId = 1,
                            ParentFolderId = 11
                        },
                        new
                        {
                            Id = 15,
                            Name = "Screenshots",
                            OwnerId = 1,
                            ParentFolderId = 12
                        },
                        new
                        {
                            Id = 16,
                            Name = "Work",
                            OwnerId = 2,
                            ParentFolderId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Personal",
                            OwnerId = 2,
                            ParentFolderId = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "Reports",
                            OwnerId = 2,
                            ParentFolderId = 16
                        },
                        new
                        {
                            Id = 19,
                            Name = "Drafts",
                            OwnerId = 2,
                            ParentFolderId = 17
                        },
                        new
                        {
                            Id = 20,
                            Name = "Archives",
                            OwnerId = 2,
                            ParentFolderId = 17
                        },
                        new
                        {
                            Id = 21,
                            Name = "Projects",
                            OwnerId = 3,
                            ParentFolderId = 3
                        },
                        new
                        {
                            Id = 22,
                            Name = "Backups",
                            OwnerId = 3,
                            ParentFolderId = 3
                        },
                        new
                        {
                            Id = 23,
                            Name = "Code",
                            OwnerId = 3,
                            ParentFolderId = 21
                        },
                        new
                        {
                            Id = 24,
                            Name = "Logs",
                            OwnerId = 3,
                            ParentFolderId = 22
                        },
                        new
                        {
                            Id = 25,
                            Name = "OldProjects",
                            OwnerId = 3,
                            ParentFolderId = 21
                        },
                        new
                        {
                            Id = 26,
                            Name = "RacingData",
                            OwnerId = 4,
                            ParentFolderId = 4
                        },
                        new
                        {
                            Id = 27,
                            Name = "Photos",
                            OwnerId = 4,
                            ParentFolderId = 4
                        },
                        new
                        {
                            Id = 28,
                            Name = "Season2023",
                            OwnerId = 4,
                            ParentFolderId = 26
                        },
                        new
                        {
                            Id = 29,
                            Name = "Season2022",
                            OwnerId = 4,
                            ParentFolderId = 26
                        },
                        new
                        {
                            Id = 30,
                            Name = "PodiumPhotos",
                            OwnerId = 4,
                            ParentFolderId = 27
                        },
                        new
                        {
                            Id = 31,
                            Name = "Videos",
                            OwnerId = 5,
                            ParentFolderId = 5
                        },
                        new
                        {
                            Id = 32,
                            Name = "Music",
                            OwnerId = 5,
                            ParentFolderId = 5
                        },
                        new
                        {
                            Id = 33,
                            Name = "Clips",
                            OwnerId = 5,
                            ParentFolderId = 31
                        },
                        new
                        {
                            Id = 34,
                            Name = "Playlists",
                            OwnerId = 5,
                            ParentFolderId = 32
                        },
                        new
                        {
                            Id = 35,
                            Name = "Concerts",
                            OwnerId = 5,
                            ParentFolderId = 32
                        },
                        new
                        {
                            Id = 36,
                            Name = "Downloads",
                            OwnerId = 6,
                            ParentFolderId = 6
                        },
                        new
                        {
                            Id = 37,
                            Name = "Archives",
                            OwnerId = 6,
                            ParentFolderId = 6
                        },
                        new
                        {
                            Id = 38,
                            Name = "Compressed",
                            OwnerId = 6,
                            ParentFolderId = 36
                        },
                        new
                        {
                            Id = 39,
                            Name = "Installers",
                            OwnerId = 6,
                            ParentFolderId = 36
                        },
                        new
                        {
                            Id = 40,
                            Name = "OldArchives",
                            OwnerId = 6,
                            ParentFolderId = 37
                        },
                        new
                        {
                            Id = 41,
                            Name = "Games",
                            OwnerId = 7,
                            ParentFolderId = 7
                        },
                        new
                        {
                            Id = 42,
                            Name = "Settings",
                            OwnerId = 7,
                            ParentFolderId = 7
                        },
                        new
                        {
                            Id = 43,
                            Name = "SaveFiles",
                            OwnerId = 7,
                            ParentFolderId = 41
                        },
                        new
                        {
                            Id = 44,
                            Name = "Mods",
                            OwnerId = 7,
                            ParentFolderId = 41
                        },
                        new
                        {
                            Id = 45,
                            Name = "Config",
                            OwnerId = 7,
                            ParentFolderId = 42
                        },
                        new
                        {
                            Id = 46,
                            Name = "Simulations",
                            OwnerId = 8,
                            ParentFolderId = 8
                        },
                        new
                        {
                            Id = 47,
                            Name = "Telemetry",
                            OwnerId = 8,
                            ParentFolderId = 8
                        },
                        new
                        {
                            Id = 48,
                            Name = "LapTimes",
                            OwnerId = 8,
                            ParentFolderId = 46
                        },
                        new
                        {
                            Id = 49,
                            Name = "Analytics",
                            OwnerId = 8,
                            ParentFolderId = 47
                        },
                        new
                        {
                            Id = 50,
                            Name = "CarSetups",
                            OwnerId = 8,
                            ParentFolderId = 46
                        },
                        new
                        {
                            Id = 51,
                            Name = "Notes",
                            OwnerId = 9,
                            ParentFolderId = 9
                        },
                        new
                        {
                            Id = 52,
                            Name = "Drafts",
                            OwnerId = 9,
                            ParentFolderId = 9
                        },
                        new
                        {
                            Id = 53,
                            Name = "Ideas",
                            OwnerId = 9,
                            ParentFolderId = 51
                        },
                        new
                        {
                            Id = 54,
                            Name = "Plans",
                            OwnerId = 9,
                            ParentFolderId = 51
                        },
                        new
                        {
                            Id = 55,
                            Name = "Templates",
                            OwnerId = 9,
                            ParentFolderId = 52
                        },
                        new
                        {
                            Id = 56,
                            Name = "Logs",
                            OwnerId = 10,
                            ParentFolderId = 10
                        },
                        new
                        {
                            Id = 57,
                            Name = "Temp",
                            OwnerId = 10,
                            ParentFolderId = 10
                        },
                        new
                        {
                            Id = 58,
                            Name = "ErrorLogs",
                            OwnerId = 10,
                            ParentFolderId = 56
                        },
                        new
                        {
                            Id = 59,
                            Name = "Cache",
                            OwnerId = 10,
                            ParentFolderId = 57
                        },
                        new
                        {
                            Id = 60,
                            Name = "SessionLogs",
                            OwnerId = 10,
                            ParentFolderId = 56
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.SharedFile", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FileId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedFiles");

                    b.HasData(
                        new
                        {
                            FileId = 8,
                            UserId = 1
                        },
                        new
                        {
                            FileId = 9,
                            UserId = 1
                        },
                        new
                        {
                            FileId = 10,
                            UserId = 1
                        },
                        new
                        {
                            FileId = 11,
                            UserId = 1
                        },
                        new
                        {
                            FileId = 14,
                            UserId = 1
                        },
                        new
                        {
                            FileId = 15,
                            UserId = 1
                        },
                        new
                        {
                            FileId = 3,
                            UserId = 2
                        },
                        new
                        {
                            FileId = 4,
                            UserId = 2
                        },
                        new
                        {
                            FileId = 5,
                            UserId = 2
                        },
                        new
                        {
                            FileId = 14,
                            UserId = 2
                        },
                        new
                        {
                            FileId = 15,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.SharedFolder", b =>
                {
                    b.Property<int>("FolderId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FolderId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedFolders");

                    b.HasData(
                        new
                        {
                            FolderId = 16,
                            UserId = 1
                        },
                        new
                        {
                            FolderId = 17,
                            UserId = 1
                        },
                        new
                        {
                            FolderId = 18,
                            UserId = 1
                        },
                        new
                        {
                            FolderId = 19,
                            UserId = 1
                        },
                        new
                        {
                            FolderId = 20,
                            UserId = 1
                        },
                        new
                        {
                            FolderId = 21,
                            UserId = 1
                        },
                        new
                        {
                            FolderId = 22,
                            UserId = 1
                        },
                        new
                        {
                            FolderId = 23,
                            UserId = 1
                        },
                        new
                        {
                            FolderId = 24,
                            UserId = 1
                        },
                        new
                        {
                            FolderId = 25,
                            UserId = 1
                        },
                        new
                        {
                            FolderId = 11,
                            UserId = 2
                        },
                        new
                        {
                            FolderId = 12,
                            UserId = 2
                        },
                        new
                        {
                            FolderId = 13,
                            UserId = 2
                        },
                        new
                        {
                            FolderId = 14,
                            UserId = 2
                        },
                        new
                        {
                            FolderId = 15,
                            UserId = 2
                        },
                        new
                        {
                            FolderId = 21,
                            UserId = 2
                        },
                        new
                        {
                            FolderId = 22,
                            UserId = 2
                        },
                        new
                        {
                            FolderId = 23,
                            UserId = 2
                        },
                        new
                        {
                            FolderId = 24,
                            UserId = 2
                        },
                        new
                        {
                            FolderId = 25,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kimi@gmail.com",
                            FirstName = "Kimi",
                            LastName = "Raikkonen",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Email = "seb@gmail.com",
                            FirstName = "Sebastian",
                            LastName = "Vettel",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 3,
                            Email = "lewis@gmail.com",
                            FirstName = "Lewis",
                            LastName = "Hamilton",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 4,
                            Email = "max@gmail.com",
                            FirstName = "Max",
                            LastName = "Verstappen",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 5,
                            Email = "charles@gmail.com",
                            FirstName = "Charles",
                            LastName = "Leclerc",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 6,
                            Email = "lando@gmail.com",
                            FirstName = "Lando",
                            LastName = "Norris",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 7,
                            Email = "fernando@gmail.com",
                            FirstName = "Fernando",
                            LastName = "Alonso",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 8,
                            Email = "george@gmail.com",
                            FirstName = "George",
                            LastName = "Russell",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 9,
                            Email = "carlos@gmail.com",
                            FirstName = "Carlos",
                            LastName = "Sainz",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 10,
                            Email = "daniel@gmail.com",
                            FirstName = "Daniel",
                            LastName = "Ricciardo",
                            Password = "1234"
                        });
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.File", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.Folder", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.FileComment", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.File", "File")
                        .WithMany("Comments")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Folder", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.Folder", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.SharedFile", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.File", "File")
                        .WithMany("SharedFiles")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.User", "User")
                        .WithMany("SharedFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.SharedFolder", b =>
                {
                    b.HasOne("Drive.Data.Entities.Models.Folder", "Folder")
                        .WithMany("SharedFolders")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Entities.Models.User", "User")
                        .WithMany("SharedFolders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.File", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("SharedFiles");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.Folder", b =>
                {
                    b.Navigation("SharedFolders");
                });

            modelBuilder.Entity("Drive.Data.Entities.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("SharedFiles");

                    b.Navigation("SharedFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
